# Records one backfill-task run result and regenerates the capture-health
# dashboard note. Called by backfill-windows-silent.vbs and
# backfill-wsl-silent.vbs with the exit code they already capture from
# sh.Run - this does not re-run or wrap the backfill itself, so a native
# crash in the backfill process (see 2026-08-19 CoreCLR crash investigation)
# still shows up here even though it can't be caught inside the backfill
# script's own try/catch.
#
# No LLM/API calls - plain state-file + Set-Content only, safe to run on
# every single backfill invocation (every 30 min x2 tasks).

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Windows", "WSL")]
    [string]$TaskLabel,

    [Parameter(Mandatory = $true)]
    [int]$ExitCode
)

$ErrorActionPreference = "Stop"

$repoRoot = "D:\_Anant\20_Progress\Documents\Jarvis"
$logsDir = Join-Path $repoRoot "30_Order\System\claude-workflow\logs"
$notePath = Join-Path $repoRoot "60_Claude\05_Clippings\AI Conversations\00 - Capture Health.md"
$maxHistory = 20
$failureWarnThreshold = 3

if (-not (Test-Path $logsDir)) {
    New-Item -ItemType Directory -Path $logsDir -Force | Out-Null
}

function Get-StatePath([string]$Label) {
    return Join-Path $logsDir "capture-health-$($Label.ToLower()).json"
}

function Add-RunRecord([string]$Label, [int]$Code) {
    $statePath = Get-StatePath $Label
    $history = @()
    if (Test-Path $statePath) {
        try {
            $raw = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json
            if ($raw) { $history = @($raw) }
        } catch {
            $history = @()
        }
    }
    $record = [PSCustomObject]@{
        timestamp = (Get-Date).ToUniversalTime().ToString("o")
        exitCode  = $Code
    }
    $history = @($history) + @($record)
    if ($history.Count -gt $maxHistory) {
        $history = $history[-$maxHistory..-1]
    }
    ($history | ConvertTo-Json -Depth 3) | Set-Content -LiteralPath $statePath -Encoding UTF8
    return $history
}

function Get-ConsecutiveFailures($history) {
    $count = 0
    for ($i = $history.Count - 1; $i -ge 0; $i--) {
        if ($history[$i].exitCode -ne 0) { $count++ } else { break }
    }
    return $count
}

function Format-TaskSection([string]$Label, $history) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("## $Label backfill")
    $lines.Add("")
    if ($history.Count -eq 0) {
        $lines.Add("_No runs recorded yet._")
        $lines.Add("")
        return $lines
    }
    $last = $history[-1]
    $consecutiveFailures = Get-ConsecutiveFailures $history
    $lastStatus = if ($last.exitCode -eq 0) { "OK (exit 0)" } else { "FAILED (exit $($last.exitCode))" }
    $lines.Add("- **Last run:** $($last.timestamp) - $lastStatus")
    if ($consecutiveFailures -ge $failureWarnThreshold) {
        $lines.Add("- **WARNING: $consecutiveFailures consecutive failures** - the automated retry (RestartCount) is not recovering this task. Investigate manually.")
    } elseif ($consecutiveFailures -gt 0) {
        $lines.Add("- $consecutiveFailures consecutive failure(s) so far, below the $failureWarnThreshold-run warning threshold.")
    } else {
        $lines.Add("- No current failure streak.")
    }
    $lines.Add("")
    $lines.Add("| Run (UTC) | Exit code |")
    $lines.Add("|---|---|")
    $takeCount = [Math]::Min(10, $history.Count)
    $recent = @($history[($history.Count - $takeCount)..($history.Count - 1)])
    for ($i = $recent.Count - 1; $i -ge 0; $i--) {
        $r = $recent[$i]
        $mark = if ($r.exitCode -eq 0) { "OK" } else { "FAILED" }
        $lines.Add("| $($r.timestamp) | $($r.exitCode) ($mark) |")
    }
    $lines.Add("")
    return $lines
}

# Only the task that actually ran gets a new record; the other task's
# history is re-read as-is so this script stays a pure recorder for
# whichever launcher invoked it.
function Read-History([string]$Label) {
    $path = Get-StatePath $Label
    if (-not (Test-Path $path)) { return @() }
    $raw = Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
    if ($null -eq $raw) { return @() }
    return @($raw)
}

if ($TaskLabel -eq "Windows") {
    $winHistory = @(Add-RunRecord -Label "Windows" -Code $ExitCode)
    $wslHistory = @(Read-History "WSL")
} else {
    $wslHistory = @(Add-RunRecord -Label "WSL" -Code $ExitCode)
    $winHistory = @(Read-History "Windows")
}

$anyWarning = (Get-ConsecutiveFailures $winHistory) -ge $failureWarnThreshold -or (Get-ConsecutiveFailures $wslHistory) -ge $failureWarnThreshold

$body = New-Object System.Collections.Generic.List[string]
$body.Add("---")
$body.Add("type: dashboard")
$body.Add("status: auto-generated")
$body.Add("tags:")
$body.Add("  - claude-code")
$body.Add("  - capture-health")
$body.Add("---")
$body.Add("# Capture Health")
$body.Add("")
$body.Add("Auto-generated by ``update-capture-health.ps1`` on every backfill run. Do not edit by hand - edits are overwritten.")
$body.Add("")
if ($anyWarning) {
    $body.Add("> [!warning] Backfill safety net is not recovering on its own")
    $body.Add("> One or both backfill tasks have failed $failureWarnThreshold+ times in a row despite Task Scheduler's automatic retry. Check Task Scheduler history and re-run manually.")
    $body.Add("")
}
$body.AddRange([string[]](Format-TaskSection "Windows" $winHistory))
$body.AddRange([string[]](Format-TaskSection "WSL" $wslHistory))

Set-Content -LiteralPath $notePath -Value ($body -join "`n") -Encoding UTF8
