/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecentEditsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  excludedFolders: [],
  backgroundFolders: [],
  lookbackDays: 7,
  enableHoverPreview: false,
  externalEditColor: "#D97757",
  pathCopyAffordance: "button",
  showSizeIndicator: false,
  sizeDeltaThresholdKb: 10,
  dayOpenMode: "open",
  rowLayout: "two-line",
  ignorePluginWrites: true
};
var VIEW_TYPE_RECENT_EDITS = "recent-edits-view";
var SUPPORTED_EXTENSIONS = /* @__PURE__ */ new Set(["md", "canvas", "base"]);
var HOVER_SOURCE = "recent-edits";
var EDITOR_CHANGE_WINDOW_MS = 5e3;
var ACTIVE_LOCAL_FILE_WINDOW_MS = 5 * 60 * 1e3;
var EXTERNAL_SYNC_GUARD_MS = 6e4;
var FILE_OPEN_WINDOW_MS = 2e3;
var PLUGIN_WRITE_WINDOW_MS = 5e3;
var CREATE_CLASSIFY_DELAY_MS = 800;
var PIN_HOVER_OPEN_MS = 250;
var PIN_HOVER_CLOSE_MS = 180;
var RecentEditsPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.editSources = {};
    this.editTimes = {};
    this.dismissedAt = {};
    // Pinned file paths. Deliberately NOT pruned by the lookback window: a pin
    // is an explicit user act and outlives the running log.
    // Only vanishes when the file does, or when the user clears it.
    this.pinned = /* @__PURE__ */ new Set();
    this.editSizes = {};
    this.sizeDeltas = {};
    this.editorChangeTimes = /* @__PURE__ */ new Map();
    this.recentFileOpens = /* @__PURE__ */ new Map();
    // Paths a plugin has declared it is about to rewrite as housekeeping, with
    // the pre-write mtime captured at declaration time. Consumed by the next
    // modify on that path; pruned with the other signal maps.
    this.pluginWrites = /* @__PURE__ */ new Map();
    this.saveDataTimer = null;
    this.midnightTimer = null;
    this.createTimers = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_RECENT_EDITS,
      (leaf) => new RecentEditsView(leaf, this)
    );
    this.addRibbonIcon("history", "Recent Edits", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open",
      name: "Open panel",
      callback: () => {
        void this.activateView();
      }
    });
    this.registerHoverLinkSource(HOVER_SOURCE, {
      display: "Recent Edits",
      defaultMod: false
    });
    this.registerEvent(
      this.app.workspace.on("editor-change", (_editor, info) => {
        const file = info?.file;
        if (file && file.path) {
          this.editorChangeTimes.set(file.path, Date.now());
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file && file.path) {
          this.recentFileOpens.set(file.path, Date.now());
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "recent-edits:plugin-write",
        (...data) => {
          const payload = data[0];
          const path = payload?.path;
          if (typeof path !== "string" || !path)
            return;
          const file = this.app.vault.getFileByPath(path);
          this.pluginWrites.set(path, {
            at: Date.now(),
            mtime: file?.stat.mtime ?? 0
          });
        }
      )
    );
    this.app.workspace.onLayoutReady(() => {
      this.registerEvent(
        this.app.vault.on("create", (file) => {
          if (!this.app.workspace.layoutReady)
            return;
          if (file instanceof import_obsidian.TFile) {
            const timer = window.setTimeout(() => {
              this.createTimers.delete(timer);
              if (this.app.vault.getAbstractFileByPath(file.path) === file) {
                this.classifyEdit(file, true);
                this.refreshViews();
              }
            }, CREATE_CLASSIFY_DELAY_MS);
            this.createTimers.add(timer);
          }
          this.refreshViews();
        })
      );
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile) {
          this.classifyEdit(file, false);
        }
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile) {
          let changed = false;
          if (this.editSources[file.path]) {
            delete this.editSources[file.path];
            changed = true;
          }
          if (this.editTimes[file.path] !== void 0) {
            delete this.editTimes[file.path];
            changed = true;
          }
          if (this.dismissedAt[file.path] !== void 0) {
            delete this.dismissedAt[file.path];
            changed = true;
          }
          if (this.editSizes[file.path] !== void 0) {
            delete this.editSizes[file.path];
            changed = true;
          }
          if (this.sizeDeltas[file.path] !== void 0) {
            delete this.sizeDeltas[file.path];
            changed = true;
          }
          if (this.pinned.delete(file.path)) {
            changed = true;
          }
          if (changed)
            this.scheduleSaveData();
        }
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile) {
          let changed = false;
          if (this.editSources[oldPath]) {
            this.editSources[file.path] = this.editSources[oldPath];
            delete this.editSources[oldPath];
            changed = true;
          }
          if (this.editTimes[oldPath] !== void 0) {
            this.editTimes[file.path] = this.editTimes[oldPath];
            delete this.editTimes[oldPath];
            changed = true;
          }
          if (this.dismissedAt[oldPath] !== void 0) {
            this.dismissedAt[file.path] = this.dismissedAt[oldPath];
            delete this.dismissedAt[oldPath];
            changed = true;
          }
          if (this.editSizes[oldPath] !== void 0) {
            this.editSizes[file.path] = this.editSizes[oldPath];
            delete this.editSizes[oldPath];
            changed = true;
          }
          if (this.sizeDeltas[oldPath] !== void 0) {
            this.sizeDeltas[file.path] = this.sizeDeltas[oldPath];
            delete this.sizeDeltas[oldPath];
            changed = true;
          }
          if (this.pinned.delete(oldPath)) {
            this.pinned.add(file.path);
            changed = true;
          }
          if (changed)
            this.scheduleSaveData();
        }
        this.refreshViews();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf && leaf.view instanceof RecentEditsView) {
          void this.reloadEditMetadata();
        }
      })
    );
    this.addSettingTab(new RecentEditsSettingTab(this.app, this));
    this.scheduleMidnightRefresh();
  }
  onunload() {
    if (this.midnightTimer !== null) {
      window.clearTimeout(this.midnightTimer);
      this.midnightTimer = null;
    }
    for (const timer of this.createTimers) {
      window.clearTimeout(timer);
    }
    this.createTimers.clear();
    if (this.saveDataTimer !== null) {
      window.clearTimeout(this.saveDataTimer);
      this.saveDataTimer = null;
      void this.persistData();
    }
  }
  scheduleMidnightRefresh() {
    if (this.midnightTimer !== null) {
      window.clearTimeout(this.midnightTimer);
    }
    const now = /* @__PURE__ */ new Date();
    const nextMidnight = new Date(
      now.getFullYear(),
      now.getMonth(),
      now.getDate() + 1,
      0,
      0,
      0,
      250
    );
    const delay = nextMidnight.getTime() - now.getTime();
    this.midnightTimer = window.setTimeout(() => {
      this.midnightTimer = null;
      this.refreshViews();
      this.scheduleMidnightRefresh();
    }, delay);
  }
  classifyEdit(file, isCreate) {
    if (!isCreate && this.settings.ignorePluginWrites) {
      const declared = this.pluginWrites.get(file.path);
      if (declared) {
        this.pluginWrites.delete(file.path);
        if (Date.now() - declared.at < PLUGIN_WRITE_WINDOW_MS) {
          if (this.editTimes[file.path] === void 0 && declared.mtime > 0) {
            this.editTimes[file.path] = declared.mtime;
          }
          this.editSizes[file.path] = file.stat.size;
          this.scheduleSaveData();
          return;
        }
      }
    }
    const lastChange = this.editorChangeTimes.get(file.path) ?? 0;
    const recentEditorChange = Date.now() - lastChange < EDITOR_CHANGE_WINDOW_MS;
    const isEmptyCreate = isCreate && file.stat.size === 0;
    const lastOpen = this.recentFileOpens.get(file.path) ?? 0;
    const recentFileOpen = Date.now() - lastOpen < FILE_OPEN_WINDOW_MS;
    const isObsidian = recentEditorChange || isEmptyCreate || recentFileOpen;
    let isLocallyOriginated = false;
    if (isObsidian) {
      isLocallyOriginated = true;
    } else if (import_obsidian.Platform.isDesktop) {
      const persisted = this.editTimes[file.path];
      if (persisted === void 0) {
        isLocallyOriginated = true;
      } else {
        const mtimeAdvance = file.stat.mtime - persisted;
        const recentLocalEditorChange = Date.now() - lastChange < ACTIVE_LOCAL_FILE_WINDOW_MS;
        if (mtimeAdvance > EXTERNAL_SYNC_GUARD_MS || recentLocalEditorChange) {
          isLocallyOriginated = true;
        }
      }
    }
    if (isLocallyOriginated) {
      this.editSources[file.path] = isObsidian ? "obsidian" : "external";
      this.editTimes[file.path] = file.stat.mtime;
      this.recordSizeDelta(file);
      this.scheduleSaveData();
    }
  }
  // Records the direction of this edit's size change vs. the file's previously
  // recorded size, then stores the new size. Called only for locally
  // originated edits so sync deliveries don't produce spurious deltas.
  recordSizeDelta(file) {
    const prev = this.editSizes[file.path];
    if (prev !== void 0) {
      const diff = file.stat.size - prev;
      const threshold = this.settings.sizeDeltaThresholdKb * 1024;
      if (diff > 0 && diff >= threshold)
        this.sizeDeltas[file.path] = "up";
      else if (diff < 0 && -diff >= threshold)
        this.sizeDeltas[file.path] = "down";
      else
        delete this.sizeDeltas[file.path];
    }
    this.editSizes[file.path] = file.stat.size;
  }
  sizeDelta(file) {
    return this.sizeDeltas[file.path];
  }
  isExternalEdit(file) {
    return this.editSources[file.path] === "external";
  }
  effectiveMtime(file) {
    return this.editTimes[file.path] ?? file.stat.mtime;
  }
  isDismissed(file) {
    return this.dismissedAt[file.path] === file.stat.mtime;
  }
  dismissFile(file) {
    this.dismissedAt[file.path] = file.stat.mtime;
    this.scheduleSaveData();
    this.refreshViews();
  }
  isPinned(file) {
    return this.pinned.has(file.path);
  }
  togglePin(file) {
    if (!this.pinned.delete(file.path))
      this.pinned.add(file.path);
    this.scheduleSaveData();
    this.refreshViews();
  }
  // Resolves pinned paths to live files, newest effective edit first.
  // Deliberately ignores the lookback window, the excluded/background folder
  // filters, and dismissals: an explicit pin outranks all of them.
  // Paths that no longer resolve are skipped here and pruned on next persist.
  pinnedFiles() {
    const files = [];
    for (const path of this.pinned) {
      const f = this.app.vault.getAbstractFileByPath(path);
      if (f instanceof import_obsidian.TFile)
        files.push(f);
    }
    files.sort((a, b) => this.effectiveMtime(b) - this.effectiveMtime(a));
    return files;
  }
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_RECENT_EDITS);
    let leaf;
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeftLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_RECENT_EDITS,
          active: true
        });
      }
    }
    if (leaf)
      await workspace.revealLeaf(leaf);
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_RECENT_EDITS).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof RecentEditsView) {
        view.scheduleRefresh();
      }
    });
  }
  async loadSettings() {
    const raw = await this.loadData() ?? {};
    const editSources = raw._editSources ?? {};
    const editTimes = raw._editTimes ?? {};
    const dismissedAt = raw._dismissedAt ?? {};
    const editSizes = raw._editSizes ?? {};
    const sizeDeltas = raw._sizeDeltas ?? {};
    const pinned = new Set(raw._pinned ?? []);
    const settingsBlob = { ...raw };
    delete settingsBlob._editSources;
    delete settingsBlob._editTimes;
    delete settingsBlob._dismissedAt;
    delete settingsBlob._editSizes;
    delete settingsBlob._sizeDeltas;
    delete settingsBlob._pinned;
    const blob = settingsBlob;
    const settings = { ...DEFAULT_SETTINGS };
    for (const key of Object.keys(DEFAULT_SETTINGS)) {
      if (blob[key] !== void 0) {
        settings[key] = blob[key];
      }
    }
    if (blob.externalEditColor === void 0 && typeof blob.claudeEditColor === "string") {
      settings.externalEditColor = blob.claudeEditColor;
    }
    this.settings = settings;
    this.editSources = editSources;
    this.editTimes = editTimes;
    this.dismissedAt = dismissedAt;
    this.editSizes = editSizes;
    this.sizeDeltas = sizeDeltas;
    this.pinned = pinned;
  }
  // Re-reads persisted edit metadata (sources, times, dismissals) from
  // data.json without disturbing in-memory settings. Used to pick up
  // changes synced in from another device.
  async reloadEditMetadata() {
    if (this.saveDataTimer !== null) {
      window.clearTimeout(this.saveDataTimer);
      this.saveDataTimer = null;
      await this.persistData();
    }
    const raw = await this.loadData() ?? {};
    const editSources = raw._editSources ?? {};
    const editTimes = raw._editTimes ?? {};
    const dismissedAt = raw._dismissedAt ?? {};
    const editSizes = raw._editSizes ?? {};
    const sizeDeltas = raw._sizeDeltas ?? {};
    const pinned = new Set(raw._pinned ?? []);
    this.editSources = editSources;
    this.editTimes = editTimes;
    this.dismissedAt = dismissedAt;
    this.editSizes = editSizes;
    this.sizeDeltas = sizeDeltas;
    this.pinned = pinned;
    this.refreshViews();
  }
  async saveSettings() {
    await this.persistData();
    this.refreshViews();
  }
  scheduleSaveData() {
    if (this.saveDataTimer !== null) {
      window.clearTimeout(this.saveDataTimer);
    }
    this.saveDataTimer = window.setTimeout(() => {
      void this.persistData();
      this.saveDataTimer = null;
    }, 500);
  }
  // Drop stale entries from the in-memory signal maps so they don't grow
  // unbounded over a long session. Kept above each map's read window.
  pruneSignalMaps() {
    const now = Date.now();
    for (const [path, t] of this.editorChangeTimes) {
      if (now - t > ACTIVE_LOCAL_FILE_WINDOW_MS)
        this.editorChangeTimes.delete(path);
    }
    for (const [path, t] of this.recentFileOpens) {
      if (now - t > FILE_OPEN_WINDOW_MS)
        this.recentFileOpens.delete(path);
    }
    for (const [path, e] of this.pluginWrites) {
      if (now - e.at > PLUGIN_WRITE_WINDOW_MS)
        this.pluginWrites.delete(path);
    }
  }
  async persistData() {
    this.pruneSignalMaps();
    const cutoff = Date.now() - this.settings.lookbackDays * 864e5;
    const freshest = (path, file) => {
      const stored = this.editTimes[path];
      return stored !== void 0 ? Math.max(stored, file.stat.mtime) : file.stat.mtime;
    };
    const prunedSources = {};
    for (const [path, src] of Object.entries(this.editSources)) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile && freshest(path, file) >= cutoff) {
        prunedSources[path] = src;
      }
    }
    this.editSources = prunedSources;
    const prunedTimes = {};
    for (const [path, mtime] of Object.entries(this.editTimes)) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile && Math.max(mtime, file.stat.mtime) >= cutoff) {
        prunedTimes[path] = mtime;
      }
    }
    this.editTimes = prunedTimes;
    const prunedDismissed = {};
    for (const [path, mtime] of Object.entries(this.dismissedAt)) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile && file.stat.mtime >= cutoff && file.stat.mtime === mtime) {
        prunedDismissed[path] = mtime;
      }
    }
    this.dismissedAt = prunedDismissed;
    const prunedSizes = {};
    for (const [path, size] of Object.entries(this.editSizes)) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile && freshest(path, file) >= cutoff) {
        prunedSizes[path] = size;
      }
    }
    this.editSizes = prunedSizes;
    const prunedDeltas = {};
    for (const [path, dir] of Object.entries(this.sizeDeltas)) {
      if (this.editSizes[path] !== void 0)
        prunedDeltas[path] = dir;
    }
    this.sizeDeltas = prunedDeltas;
    if (this.app.workspace.layoutReady) {
      const prunedPins = /* @__PURE__ */ new Set();
      for (const path of this.pinned) {
        if (this.app.vault.getAbstractFileByPath(path) instanceof import_obsidian.TFile) {
          prunedPins.add(path);
        }
      }
      this.pinned = prunedPins;
    }
    await this.saveData({
      ...this.settings,
      _editSources: this.editSources,
      _editTimes: this.editTimes,
      _dismissedAt: this.dismissedAt,
      _editSizes: this.editSizes,
      _sizeDeltas: this.sizeDeltas,
      _pinned: [...this.pinned]
    });
  }
};
var RecentEditsView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.collapsedDays = /* @__PURE__ */ new Set();
    this.showBackgroundFolders = false;
    this.refreshTimer = null;
    // Pinned drawer. `Open` is the live visual state (survives re-render);
    // `Locked` means the user clicked to hold it open, so hover-out won't close.
    this.pinDrawerOpen = false;
    this.pinDrawerLocked = false;
    this.pinOpenTimer = null;
    this.pinCloseTimer = null;
    this.pinDrawerEl = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_RECENT_EDITS;
  }
  getDisplayText() {
    return "Recent Edits";
  }
  getIcon() {
    return "history";
  }
  async onOpen() {
    await this.plugin.reloadEditMetadata();
    this.render();
  }
  async onClose() {
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
    }
    this.clearPinTimers();
    this.pinDrawerEl = null;
  }
  showFileMenu(evt, file) {
    const menu = new import_obsidian.Menu();
    const { workspace } = this.app;
    menu.addItem(
      (item) => item.setTitle("Open in new tab").setIcon("lucide-file-plus").onClick(() => {
        void workspace.getLeaf("tab").openFile(file);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Open to the right").setIcon("lucide-separator-vertical").onClick(() => {
        void workspace.getLeaf("split", "vertical").openFile(file);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Open in new window").setIcon("lucide-monitor").onClick(() => {
        void workspace.getLeaf("window").openFile(file);
      })
    );
    workspace.trigger("file-menu", menu, file, "file-explorer-context-menu");
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Copy path").setIcon("lucide-copy").onClick(() => {
        void navigator.clipboard.writeText(file.path).then(() => {
        }, () => new import_obsidian.Notice("Copy failed"));
      })
    );
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Rename\u2026").setIcon("lucide-pencil").onClick(() => {
        new RenameFileModal(this.app, file).open();
      })
    );
    menu.addItem(
      (item) => item.setTitle("Delete").setIcon("lucide-trash-2").onClick(() => {
        new ConfirmDeleteModal(this.app, file).open();
      })
    );
    menu.addSeparator();
    const pinned = this.plugin.isPinned(file);
    menu.addItem(
      (item) => item.setTitle(pinned ? "Unpin" : "Pin").setIcon("lucide-pin").onClick(() => {
        this.plugin.togglePin(file);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Clear from list").setIcon("lucide-eye-off").onClick(() => {
        this.plugin.dismissFile(file);
      })
    );
    menu.showAtMouseEvent(evt);
  }
  async openInNewTab(file) {
    const workspace = this.app.workspace;
    const leaf = workspace.getLeaf("tab");
    await leaf.openFile(file);
    workspace.setActiveLeaf(leaf, { focus: true });
  }
  findLeafForFile(file) {
    let found = null;
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (found)
        return;
      const state = leaf.getViewState().state;
      if (state?.file === file.path) {
        found = leaf;
      }
    });
    return found;
  }
  scheduleRefresh() {
    if (this.refreshTimer !== null) {
      window.clearTimeout(this.refreshTimer);
    }
    this.refreshTimer = window.setTimeout(() => {
      this.render();
      this.refreshTimer = null;
    }, 200);
  }
  getRecentFiles() {
    const { lookbackDays, excludedFolders, backgroundFolders } = this.plugin.settings;
    const cutoff = Date.now() - lookbackDays * 864e5;
    const showBg = this.showBackgroundFolders;
    const matchesFolder = (path, folder) => {
      const norm = folder.replace(/^\/+|\/+$/g, "");
      if (!norm)
        return false;
      return path === norm || path.startsWith(norm + "/");
    };
    const all = this.app.vault.getFiles();
    const filtered = all.filter((f) => {
      if (!SUPPORTED_EXTENSIONS.has(f.extension))
        return false;
      const effective = this.plugin.effectiveMtime(f);
      if (Math.max(f.stat.mtime, effective) < cutoff)
        return false;
      const segs = f.path.split("/");
      for (let i = 0; i < segs.length - 1; i++) {
        if (segs[i].startsWith("."))
          return false;
      }
      for (const ex of excludedFolders) {
        if (matchesFolder(f.path, ex))
          return false;
      }
      if (!showBg) {
        for (const bg of backgroundFolders) {
          if (matchesFolder(f.path, bg))
            return false;
        }
      }
      if (this.plugin.isDismissed(f))
        return false;
      return true;
    });
    const groupsMap = /* @__PURE__ */ new Map();
    for (const f of filtered) {
      const d = new Date(this.plugin.effectiveMtime(f));
      const key = formatDayKey(d);
      let g = groupsMap.get(key);
      if (!g) {
        g = { key, date: startOfLocalDay(d), files: [] };
        groupsMap.set(key, g);
      }
      g.files.push(f);
    }
    const groups = Array.from(groupsMap.values());
    groups.sort((a, b) => b.date.getTime() - a.date.getTime());
    for (const g of groups) {
      g.files.sort(
        (a, b) => this.plugin.effectiveMtime(b) - this.plugin.effectiveMtime(a)
      );
    }
    return groups;
  }
  // Renders the day-mode + gear controls into a header element. Placed on the
  // top day header (or the empty-state bar) so they share an existing row and
  // cost no extra vertical space. Re-drawn on every render, so cycleDayMode
  // just re-renders to update the icon.
  renderControls(target) {
    const controls = target.createDiv({ cls: "recent-edits-controls" });
    const mode = this.plugin.settings.dayOpenMode;
    const modeBtn = controls.createDiv({
      cls: "clickable-icon recent-edits-control-btn",
      attr: { role: "button", tabindex: "0", "aria-label": dayModeLabel(mode) }
    });
    (0, import_obsidian.setIcon)(modeBtn, dayModeIcon(mode));
    const cycle = (evt) => {
      evt.stopPropagation();
      void this.cycleDayMode();
    };
    modeBtn.addEventListener("click", cycle);
    modeBtn.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" || evt.key === " ") {
        evt.preventDefault();
        cycle(evt);
      }
    });
    const gearBtn = controls.createDiv({
      cls: "clickable-icon recent-edits-control-btn",
      attr: { role: "button", tabindex: "0", "aria-label": "Open settings" }
    });
    (0, import_obsidian.setIcon)(gearBtn, "settings");
    const open = (evt) => {
      evt.stopPropagation();
      this.openSettings();
    };
    gearBtn.addEventListener("click", open);
    gearBtn.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" || evt.key === " ") {
        evt.preventDefault();
        open(evt);
      }
    });
  }
  // The "Pinned" pill plus the drawer it reveals. The pill sits in the day
  // header immediately left of the background-folders "More" pill; the drawer
  // is a sibling of that header, so it hangs directly beneath it.
  //
  // Two positioning modes, deliberately different:
  //   - hover peek: absolutely positioned, so it overlays the list and nothing
  //     reflows out from under the cursor mid-hover.
  //   - locked open: back in normal flow, so the day list moves down and sits
  //     below the pinned section instead of being covered by it.
  // The absolute case sets no `top`, so the box lands at its static position:
  // the same place it occupies when locked. One layout, two stacking modes.
  renderPinnedControl(pillHost, flowParent) {
    const files = this.plugin.pinnedFiles();
    const pill = pillHost.createSpan({
      cls: "recent-edits-bg-toggle recent-edits-pin-toggle",
      attr: {
        role: "button",
        tabindex: "0",
        // Hover already reveals the drawer, so the tooltip has to carry the
        // one thing hovering can't tell you: that clicking holds it open.
        "aria-label": this.pinDrawerLocked ? "Pinned notes. Click to close." : "Pinned notes. Click to keep open.",
        "aria-expanded": String(this.pinDrawerOpen)
      }
    });
    if (files.length > 0)
      pill.addClass("has-pins");
    if (this.pinDrawerOpen)
      pill.addClass("is-active");
    const pillIcon = pill.createSpan({ cls: "recent-edits-bg-toggle-icon" });
    (0, import_obsidian.setIcon)(pillIcon, "pin");
    pill.createSpan({
      cls: "recent-edits-bg-toggle-label",
      text: "Pinned"
    });
    const drawer = flowParent.createDiv({ cls: "recent-edits-pin-drawer" });
    drawer.addEventListener("click", (evt) => evt.stopPropagation());
    this.pinDrawerEl = drawer;
    if (this.pinDrawerOpen)
      drawer.dataset.open = "true";
    if (this.pinDrawerLocked)
      drawer.addClass("is-locked");
    const head = drawer.createDiv({ cls: "recent-edits-pin-drawer-head" });
    head.createSpan({
      cls: "recent-edits-pin-drawer-title",
      text: "Pinned"
    });
    if (files.length > 0) {
      head.createSpan({
        cls: "recent-edits-pin-drawer-count",
        text: String(files.length)
      });
    }
    const list = drawer.createDiv({ cls: "recent-edits-pin-drawer-list" });
    if (files.length === 0) {
      list.createDiv({
        cls: "recent-edits-pin-drawer-empty",
        text: "No pinned notes. Right-click a row, or use its pin."
      });
    } else {
      for (const f of files) {
        this.renderFileRow(list, f, { relativeStamp: true });
      }
      list.addEventListener("click", () => {
        if (!this.pinDrawerLocked)
          this.setPinDrawerOpen(false);
      });
    }
    const cancelTimers = () => {
      if (this.pinOpenTimer !== null) {
        window.clearTimeout(this.pinOpenTimer);
        this.pinOpenTimer = null;
      }
      if (this.pinCloseTimer !== null) {
        window.clearTimeout(this.pinCloseTimer);
        this.pinCloseTimer = null;
      }
    };
    const scheduleOpen = () => {
      if (this.pinDrawerLocked || this.pinDrawerOpen)
        return;
      cancelTimers();
      this.pinOpenTimer = window.setTimeout(() => {
        this.pinOpenTimer = null;
        this.setPinDrawerOpen(true);
      }, PIN_HOVER_OPEN_MS);
    };
    const scheduleClose = () => {
      if (this.pinDrawerLocked)
        return;
      cancelTimers();
      this.pinCloseTimer = window.setTimeout(() => {
        this.pinCloseTimer = null;
        this.setPinDrawerOpen(false);
      }, PIN_HOVER_CLOSE_MS);
    };
    pill.addEventListener("mouseenter", scheduleOpen);
    pill.addEventListener("mouseleave", scheduleClose);
    drawer.addEventListener("mouseenter", cancelTimers);
    drawer.addEventListener("mouseleave", scheduleClose);
    const toggleLock = (evt) => {
      evt.stopPropagation();
      cancelTimers();
      this.pinDrawerLocked = !this.pinDrawerLocked;
      this.setPinDrawerOpen(this.pinDrawerLocked);
      drawer.toggleClass("is-locked", this.pinDrawerLocked);
      pill.setAttribute(
        "aria-label",
        this.pinDrawerLocked ? "Pinned notes. Click to close." : "Pinned notes. Click to keep open."
      );
    };
    pill.addEventListener("click", toggleLock);
    pill.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" || evt.key === " ") {
        evt.preventDefault();
        toggleLock(evt);
      }
      if (evt.key === "Escape" && this.pinDrawerOpen) {
        this.pinDrawerLocked = false;
        this.setPinDrawerOpen(false);
      }
    });
  }
  setPinDrawerOpen(open) {
    this.pinDrawerOpen = open;
    const el = this.pinDrawerEl;
    if (!el)
      return;
    if (open)
      el.dataset.open = "true";
    else
      delete el.dataset.open;
    const pill = this.contentEl.querySelector(
      ".recent-edits-pin-toggle"
    );
    pill?.setAttribute("aria-expanded", String(open));
    pill?.toggleClass("is-active", open);
  }
  clearPinTimers() {
    if (this.pinOpenTimer !== null) {
      window.clearTimeout(this.pinOpenTimer);
      this.pinOpenTimer = null;
    }
    if (this.pinCloseTimer !== null) {
      window.clearTimeout(this.pinCloseTimer);
      this.pinCloseTimer = null;
    }
  }
  openSettings() {
    const setting = this.app.setting;
    setting?.open();
    setting?.openTabById(this.plugin.manifest.id);
  }
  async cycleDayMode() {
    const order = ["open", "collapsed", "hover"];
    const idx = order.indexOf(this.plugin.settings.dayOpenMode);
    this.plugin.settings.dayOpenMode = order[(idx + 1) % order.length];
    this.collapsedDays.clear();
    await this.plugin.saveSettings();
  }
  render() {
    const container = this.contentEl;
    this.clearPinTimers();
    this.pinDrawerEl = null;
    container.empty();
    container.addClass("recent-edits-container");
    container.style.setProperty(
      "--recent-edits-dot-color",
      this.plugin.settings.externalEditColor
    );
    container.dataset.dayMode = this.plugin.settings.dayOpenMode;
    container.dataset.rowLayout = this.plugin.settings.rowLayout;
    const hasBackground = this.plugin.settings.backgroundFolders.length > 0;
    const groups = this.getRecentFiles();
    if (groups.length === 0) {
      const wrap = container.createDiv({
        cls: "recent-edits-empty-controls-wrap"
      });
      const bar = wrap.createDiv({ cls: "recent-edits-empty-controls" });
      this.renderPinnedControl(bar, wrap);
      this.renderControls(bar);
      const days = this.plugin.settings.lookbackDays;
      const empty = container.createDiv({ cls: "recent-edits-empty" });
      empty.setText(
        `No edits in the last ${days} day${days === 1 ? "" : "s"}.`
      );
      if (hasBackground && !this.showBackgroundFolders) {
        const action = container.createDiv({
          cls: "recent-edits-empty-action"
        });
        const link = action.createEl("a", { text: "Show background folders" });
        link.addEventListener("click", (evt) => {
          evt.preventDefault();
          this.showBackgroundFolders = true;
          this.render();
        });
      }
      return;
    }
    const list = container.createDiv({ cls: "recent-edits-list" });
    groups.forEach((g, i) => {
      this.renderGroup(list, g, hasBackground, i === 0);
    });
  }
  renderGroup(parent, g, withBgToggle, isFirst) {
    const groupEl = parent.createDiv({ cls: "recent-edits-group" });
    const defaultCollapsed = this.plugin.settings.dayOpenMode !== "open";
    const isCollapsed = () => defaultCollapsed !== this.collapsedDays.has(g.key);
    if (isCollapsed())
      groupEl.dataset.collapsed = "true";
    const headerWrap = groupEl.createDiv({ cls: "recent-edits-header-wrap" });
    const header = headerWrap.createDiv({ cls: "recent-edits-day-header" });
    const chevron = header.createSpan({ cls: "recent-edits-chevron" });
    (0, import_obsidian.setIcon)(chevron, "chevron-down");
    header.createSpan({
      cls: "recent-edits-day-label",
      text: formatDayLabel(g.date)
    });
    if (isFirst)
      this.renderPinnedControl(header, headerWrap);
    if (withBgToggle) {
      const toggle = header.createSpan({ cls: "recent-edits-bg-toggle" });
      if (this.showBackgroundFolders)
        toggle.addClass("is-active");
      const iconEl = toggle.createSpan({
        cls: "recent-edits-bg-toggle-icon"
      });
      (0, import_obsidian.setIcon)(iconEl, "archive");
      toggle.createSpan({
        cls: "recent-edits-bg-toggle-label",
        text: this.showBackgroundFolders ? "Less" : "More"
      });
      toggle.setAttribute(
        "aria-label",
        this.showBackgroundFolders ? "Hide background folders" : "Show background folders"
      );
      toggle.addEventListener("click", (evt) => {
        evt.stopPropagation();
        this.showBackgroundFolders = !this.showBackgroundFolders;
        this.render();
      });
    }
    header.createSpan({
      cls: "recent-edits-day-count",
      text: String(g.files.length)
    });
    if (isFirst)
      this.renderControls(header);
    header.addEventListener("click", () => {
      if (this.collapsedDays.has(g.key))
        this.collapsedDays.delete(g.key);
      else
        this.collapsedDays.add(g.key);
      if (isCollapsed())
        groupEl.dataset.collapsed = "true";
      else
        delete groupEl.dataset.collapsed;
    });
    const filesEl = groupEl.createDiv({ cls: "recent-edits-day-files" });
    for (const f of g.files) {
      this.renderFileRow(filesEl, f);
    }
  }
  // `relativeStamp` is set for rows that sit outside a day group (the pinned
  // drawer), where a bare clock time would imply the edit happened today.
  renderFileRow(parent, file, opts = {}) {
    const row = parent.createDiv({ cls: "recent-edits-row" });
    if (this.plugin.isExternalEdit(file)) {
      row.addClass("is-external-edit");
    }
    const info = row.createDiv({ cls: "recent-edits-row-info" });
    const nameLine = info.createDiv({ cls: "recent-edits-row-nameline" });
    const name = nameLine.createDiv({
      cls: "recent-edits-row-name",
      text: file.basename
    });
    name.setAttribute("title", file.path);
    if (this.plugin.settings.showSizeIndicator) {
      const dir = this.plugin.sizeDelta(file);
      if (dir) {
        const sizeEl = nameLine.createSpan({
          cls: `recent-edits-size-delta is-${dir}`,
          attr: {
            "aria-label": dir === "up" ? "Larger than previous edit" : "Smaller than previous edit"
          }
        });
        (0, import_obsidian.setIcon)(sizeEl, dir === "up" ? "chevron-up" : "chevron-down");
      }
    }
    const oneLine = this.plugin.settings.rowLayout === "one-line";
    let pathEl = null;
    if (!oneLine) {
      const folderPath = file.parent ? file.parent.path : "";
      const displayPath = folderPath === "" || folderPath === "/" ? "/" : folderPath + "/";
      pathEl = info.createDiv({
        cls: "recent-edits-row-path",
        text: displayPath
      });
    }
    const affordance = this.plugin.settings.pathCopyAffordance;
    const canCopyAbsolute = import_obsidian.Platform.isDesktopApp;
    const showButton = canCopyAbsolute && (oneLine || affordance === "button" || affordance === "both");
    const pathTextIsCopyTarget = !oneLine && canCopyAbsolute && (affordance === "path-text" || affordance === "both");
    const copyAbsolutePath = async (evt) => {
      evt.stopPropagation();
      const adapter = this.app.vault.adapter;
      if (adapter instanceof import_obsidian.FileSystemAdapter) {
        const fullPath = adapter.getFullPath(file.path);
        try {
          await navigator.clipboard.writeText(fullPath);
          new import_obsidian.Notice("Path copied");
        } catch {
          new import_obsidian.Notice("Copy failed");
        }
      } else {
        new import_obsidian.Notice("Absolute path unavailable on this platform");
      }
    };
    if (pathTextIsCopyTarget && pathEl) {
      pathEl.addClass("is-copy-target");
      pathEl.setAttribute("aria-label", "Click to copy absolute path");
      pathEl.addEventListener("click", (evt) => {
        void copyAbsolutePath(evt);
      });
    }
    const meta = row.createDiv({ cls: "recent-edits-row-meta" });
    meta.addClass("has-button");
    const actions = meta.createDiv({ cls: "recent-edits-row-actions" });
    const isPinned = this.plugin.isPinned(file);
    const pinBtn = actions.createDiv({
      cls: "recent-edits-row-pin-btn",
      attr: {
        role: "button",
        tabindex: "0",
        // State first, then the action: the icon alone can't say which it is.
        "aria-label": isPinned ? "Pinned. Click to unpin." : "Not pinned. Click to pin."
      }
    });
    if (isPinned)
      pinBtn.addClass("is-pinned");
    (0, import_obsidian.setIcon)(pinBtn, "pin");
    const togglePin = (evt) => {
      evt.stopPropagation();
      this.plugin.togglePin(file);
    };
    pinBtn.addEventListener("click", togglePin);
    pinBtn.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" || evt.key === " ") {
        evt.preventDefault();
        togglePin(evt);
      }
    });
    if (showButton) {
      const btn = actions.createDiv({
        cls: "recent-edits-row-copy-btn",
        attr: {
          role: "button",
          tabindex: "0",
          "aria-label": "Copy absolute path"
        }
      });
      (0, import_obsidian.setIcon)(btn, "link");
      btn.addEventListener("click", (evt) => {
        void copyAbsolutePath(evt);
      });
      btn.addEventListener("keydown", (evt) => {
        if (evt.key === "Enter" || evt.key === " ") {
          evt.preventDefault();
          void copyAbsolutePath(evt);
        }
      });
    }
    const stamp = new Date(this.plugin.effectiveMtime(file));
    const timeEl = meta.createSpan({
      cls: "recent-edits-row-time",
      text: opts.relativeStamp ? formatRelativeStamp(stamp) : formatTime12h(stamp)
    });
    if (opts.relativeStamp) {
      timeEl.setAttribute(
        "title",
        `${formatDayKey(stamp)} ${formatTime12h(stamp)}`
      );
    }
    row.addEventListener("click", (evt) => {
      const forceNewTab = evt.metaKey || evt.ctrlKey;
      if (!forceNewTab) {
        const existing = this.findLeafForFile(file);
        if (existing) {
          this.app.workspace.setActiveLeaf(existing, { focus: true });
          return;
        }
      }
      void this.openInNewTab(file);
    });
    row.addEventListener("contextmenu", (evt) => {
      evt.preventDefault();
      this.showFileMenu(evt, file);
    });
    if (this.plugin.settings.enableHoverPreview) {
      row.addEventListener("mouseover", (evt) => {
        this.app.workspace.trigger("hover-link", {
          event: evt,
          source: HOVER_SOURCE,
          hoverParent: this,
          targetEl: row,
          linktext: file.path
        });
      });
    }
  }
};
var RecentEditsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  // Declarative settings (Obsidian 1.13+). Obsidian renders, indexes for
  // search, and persists these; display() is deprecated and intentionally gone.
  getSettingDefinitions() {
    return [
      // The first group carries no heading by convention. Lookback sits alone
      // because it is the only setting that changes what the panel contains
      // rather than how it is drawn.
      {
        name: "Lookback days",
        desc: "How many days back to show.",
        aliases: ["window", "range", "history"],
        control: {
          type: "number",
          key: "lookbackDays",
          defaultValue: DEFAULT_SETTINGS.lookbackDays,
          min: 1,
          max: 90,
          validate: (v) => Number.isFinite(v) && v >= 1 && v <= 90 ? void 0 : "Enter a whole number between 1 and 90."
        }
      },
      {
        type: "group",
        heading: "Row display",
        items: [
          {
            name: "Row layout",
            desc: "Two lines shows the folder path beneath the filename. One line drops the path to fit more entries on screen and moves the time onto the filename row; the full path is still available by hovering the filename.",
            aliases: ["compact", "density", "one line", "two line"],
            control: {
              type: "dropdown",
              key: "rowLayout",
              defaultValue: DEFAULT_SETTINGS.rowLayout,
              options: {
                "two-line": "Two lines (filename + path)",
                "one-line": "One line (filename only)"
              }
            }
          },
          {
            name: "External edit indicator color",
            desc: "Color of the dot shown next to files edited from outside Obsidian (filesystem writes, sync, plugins). Default is Anthropic orange.",
            aliases: ["dot", "indicator"],
            control: {
              type: "color",
              key: "externalEditColor",
              defaultValue: DEFAULT_SETTINGS.externalEditColor
            }
          },
          {
            name: "File size change indicator",
            desc: "Show a subtle up/down chevron on each row indicating whether the file grew (green) or shrank (red) since its previous edit.",
            aliases: ["chevron", "grew", "shrank"],
            control: {
              type: "toggle",
              key: "showSizeIndicator",
              defaultValue: DEFAULT_SETTINGS.showSizeIndicator
            }
          },
          {
            name: "Size change threshold (KB)",
            desc: "Minimum change, in KB, for a row to show the up/down indicator. Smaller changes are ignored.",
            // Meaningless while the indicator is off. Re-evaluated by the
            // refreshDomState() call in setControlValue, which is a CSS-state
            // toggle rather than a rebuild, so the pane does not jump.
            visible: () => this.plugin.settings.showSizeIndicator,
            control: {
              type: "number",
              key: "sizeDeltaThresholdKb",
              defaultValue: DEFAULT_SETTINGS.sizeDeltaThresholdKb,
              min: 0,
              step: "any",
              validate: (v) => Number.isFinite(v) && v >= 0 ? void 0 : "Enter zero or a positive number."
            }
          },
          {
            name: "Copy absolute path affordance",
            desc: "How to expose the 'copy absolute path to clipboard' action on each row. The button is an explicit, always-visible target; the folder-path text is a subtler invisible affordance. Use Both to expose both. One-line row layout always uses the button, since there is no path text to click.",
            aliases: ["clipboard", "path"],
            control: {
              type: "dropdown",
              key: "pathCopyAffordance",
              defaultValue: DEFAULT_SETTINGS.pathCopyAffordance,
              options: {
                button: "Button above the time",
                "path-text": "Folder-path text",
                both: "Both"
              }
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Behavior",
        items: [
          {
            name: "Hover preview",
            desc: "Show Obsidian's page preview popup when hovering an entry. Requires the Page Preview core plugin.",
            aliases: ["popup", "peek"],
            control: {
              type: "toggle",
              key: "enableHoverPreview",
              defaultValue: DEFAULT_SETTINGS.enableHoverPreview
            }
          },
          {
            name: "Ignore plugin-declared writes",
            desc: "When a plugin announces that it is about to rewrite a note as housekeeping (reordering or scaffolding frontmatter, for example), leave the entry as it was: no time bump, no dot. Plugins opt in by firing the recent-edits:plugin-write event; see the README.",
            aliases: ["housekeeping", "frontmatter", "reconcile", "announce", "plugin"],
            control: {
              type: "toggle",
              key: "ignorePluginWrites",
              defaultValue: DEFAULT_SETTINGS.ignorePluginWrites
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Filtering",
        items: [
          {
            name: "Background folders",
            desc: "Folders hidden by default. Use the toggle in the panel header to show them temporarily. Useful for files that update often but you only check occasionally.",
            aliases: ["hidden", "noisy", "more"],
            render: (setting) => this.renderFolderList(setting, {
              getValue: () => this.plugin.settings.backgroundFolders,
              setValue: async (v) => {
                this.plugin.settings.backgroundFolders = v;
                await this.plugin.saveSettings();
              },
              datalistId: "recent-edits-background-folder-list"
            })
          },
          {
            name: "Excluded folders",
            desc: `Folders hidden from the list completely. Dot-prefixed folders (${this.app.vault.configDir}, .trash) are always excluded.`,
            aliases: ["ignore", "hide"],
            render: (setting) => this.renderFolderList(setting, {
              getValue: () => this.plugin.settings.excludedFolders,
              setValue: async (v) => {
                this.plugin.settings.excludedFolders = v;
                await this.plugin.saveSettings();
              },
              datalistId: "recent-edits-excluded-folder-list"
            })
          }
        ]
      },
      ...this.supportGroup()
    ];
  }
  // Settings live on plugin.settings, but the plugin's own persistData() also
  // writes the private _editSources / _editTimes / _pinned maps in the same
  // data.json. The inherited implementation would call saveData() with the
  // settings object alone and drop all of them, taking every pin and
  // classification with it. Route both directions through the plugin instead.
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    this.plugin.settings[key] = value;
    await this.plugin.saveSettings();
    this.refreshDomState();
  }
  // Last group, and omitted entirely when the manifest carries no fundingUrl.
  supportGroup() {
    const funding = this.plugin.manifest.fundingUrl;
    const url = typeof funding === "string" ? funding : Object.values(funding ?? {}).find((v) => typeof v === "string");
    if (!url)
      return [];
    return [
      {
        type: "group",
        heading: "Support",
        items: [
          {
            name: "Buy me a coffee",
            desc: "Recent Edits is free and always will be. If it earns a place in your daily workflow, a coffee helps keep it maintained.",
            aliases: ["donate", "ko-fi", "kofi", "support"],
            render: (setting) => {
              const link = setting.controlEl.createEl("a", {
                cls: "recent-edits-kofi",
                href: url,
                attr: {
                  target: "_blank",
                  rel: "noopener noreferrer",
                  "aria-label": "Support Recent Edits on Ko-fi"
                }
              });
              link.setAttribute("title", "Buy me a coffee at ko-fi.com");
            }
          }
        ]
      }
    ];
  }
  // Chip picker for a string[] setting. A `render` escape hatch rather than a
  // declarative control: no built-in control persists an array of folder
  // paths, and `list` would mean rebuilding a working UI. Note that `render`
  // rows do NOT auto-save, so every mutation goes through opts.setValue.
  renderFolderList(setting, opts) {
    setting.settingEl.addClass("recent-edits-folder-setting");
    const wrapper = setting.settingEl.createDiv({
      cls: "recent-edits-folder-list"
    });
    const chipContainer = wrapper.createDiv({
      cls: "recent-edits-chip-container"
    });
    const renderChips = () => {
      chipContainer.empty();
      const values = opts.getValue();
      if (values.length === 0) {
        chipContainer.createSpan({
          cls: "recent-edits-chip-empty",
          text: "None."
        });
        return;
      }
      for (const folder of values) {
        const chip = chipContainer.createSpan({ cls: "recent-edits-chip" });
        chip.createSpan({
          cls: "recent-edits-chip-label",
          text: folder
        });
        const x = chip.createSpan({
          cls: "recent-edits-chip-x",
          text: "\xD7"
        });
        x.setAttribute("aria-label", `Remove ${folder}`);
        x.addEventListener("click", () => {
          void opts.setValue(opts.getValue().filter((f) => f !== folder)).then(() => renderChips());
        });
      }
    };
    renderChips();
    const inputWrapper = wrapper.createDiv({
      cls: "recent-edits-folder-input-wrapper"
    });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "recent-edits-folder-input",
      attr: { placeholder: "Type a folder path\u2026" }
    });
    const datalist = inputWrapper.createEl("datalist", {
      attr: { id: opts.datalistId }
    });
    input.setAttribute("list", opts.datalistId);
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((f) => f.path).filter((p) => p && p !== "/").sort();
    for (const path of folders) {
      datalist.createEl("option", { value: path });
    }
    const addBtn = inputWrapper.createEl("button", {
      cls: "recent-edits-add-btn mod-cta",
      text: "Add"
    });
    const addCurrent = async () => {
      const trimmed = input.value.trim();
      if (!trimmed)
        return;
      const val = (0, import_obsidian.normalizePath)(trimmed).replace(/^\/+/, "");
      if (!val || val === "/")
        return;
      if (!opts.getValue().includes(val)) {
        await opts.setValue([...opts.getValue(), val]);
        renderChips();
      }
      input.value = "";
      input.focus();
    };
    addBtn.addEventListener("click", () => {
      void addCurrent();
    });
    input.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        void addCurrent();
      }
    });
  }
};
function formatDayKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}
function startOfLocalDay(d) {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}
function formatDayLabel(d) {
  const today = startOfLocalDay(/* @__PURE__ */ new Date());
  const diff = Math.round((today.getTime() - d.getTime()) / 864e5);
  if (diff === 0)
    return "Today";
  if (diff === 1)
    return "Yesterday";
  return `${formatDayKey(d)} (${WEEKDAYS[d.getDay()]})`;
}
var WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
var MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec"
];
function formatRelativeStamp(d) {
  const today = startOfLocalDay(/* @__PURE__ */ new Date());
  const diff = Math.round(
    (today.getTime() - startOfLocalDay(d).getTime()) / 864e5
  );
  if (diff === 0)
    return formatTime12h(d);
  if (diff > 0 && diff < 7)
    return WEEKDAYS[d.getDay()];
  const stamp = `${MONTHS[d.getMonth()]} ${d.getDate()}`;
  return d.getFullYear() === today.getFullYear() ? stamp : `${stamp}, ${d.getFullYear()}`;
}
function formatTime12h(d) {
  let h = d.getHours();
  const m = d.getMinutes();
  const ampm = h >= 12 ? "PM" : "AM";
  h = h % 12;
  if (h === 0)
    h = 12;
  return `${h}:${String(m).padStart(2, "0")} ${ampm}`;
}
function dayModeIcon(mode) {
  switch (mode) {
    case "open":
      return "chevrons-up-down";
    case "collapsed":
      return "chevrons-down-up";
    case "hover":
      return "eye";
  }
}
function dayModeLabel(mode) {
  switch (mode) {
    case "open":
      return "Days: expanded. Click to collapse by default.";
    case "collapsed":
      return "Days: collapsed. Click to reveal on hover.";
    case "hover":
      return "Days: reveal on hover. Click to expand.";
  }
}
var RenameFileModal = class extends import_obsidian.Modal {
  constructor(app, file) {
    super(app);
    this.file = file;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Rename file");
    contentEl.createEl("p", {
      cls: "recent-edits-modal-current",
      text: this.file.path
    });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      cls: "recent-edits-modal-input"
    });
    inputEl.value = this.file.basename;
    const buttonRow = contentEl.createDiv({ cls: "recent-edits-modal-buttons" });
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    const renameBtn = buttonRow.createEl("button", {
      cls: "mod-cta",
      text: "Rename"
    });
    const submit = async () => {
      const newName = inputEl.value.trim();
      if (!newName || newName === this.file.basename) {
        this.close();
        return;
      }
      const parentPath = this.file.parent?.path ?? "";
      const parentPrefix = parentPath && parentPath !== "/" ? `${parentPath}/` : "";
      const newPath = (0, import_obsidian.normalizePath)(
        `${parentPrefix}${newName}.${this.file.extension}`
      );
      await this.app.fileManager.renameFile(this.file, newPath);
      this.close();
    };
    renameBtn.addEventListener("click", () => {
      void submit();
    });
    cancelBtn.addEventListener("click", () => this.close());
    inputEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter") {
        evt.preventDefault();
        void submit();
      } else if (evt.key === "Escape") {
        evt.preventDefault();
        this.close();
      }
    });
    window.setTimeout(() => {
      inputEl.focus();
      inputEl.select();
    }, 0);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ConfirmDeleteModal = class extends import_obsidian.Modal {
  constructor(app, file) {
    super(app);
    this.file = file;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Delete file");
    contentEl.createEl("p", {
      text: `Delete "${this.file.path}"?`
    });
    contentEl.createEl("p", {
      cls: "recent-edits-modal-note",
      text: "This follows your Files & Links deleted-file preference (system trash, .trash folder, or permanent delete)."
    });
    const buttonRow = contentEl.createDiv({ cls: "recent-edits-modal-buttons" });
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    const deleteBtn = buttonRow.createEl("button", {
      cls: "mod-warning",
      text: "Delete"
    });
    deleteBtn.addEventListener("click", () => {
      void this.app.fileManager.trashFile(this.file).then(() => this.close());
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};

/* nosourcemap */